#!/bin/bash
set -euo pipefail


pushd ./test

rm -rf build || true

# from https://dr-kino.github.io/2019/12/22/test-coverage-using-gtest-gcov-and-lcov/
mkdir -p build && cd build && cmake ..
make init
make gcov
make lcov

popd

find ./test/build/lcoverage