#!/bin/bash
set -euo pipefail

# install lcov
if ! which lcov ; then
    sudo apt-get install -y lcov
fi

# install gmock
if ! ls /usr/include/gmock ; then

    sudo apt-get install -y libboost-all-dev libgmock-dev
    find /usr/lib/ -name '*gmock*'
    find /usr/include/gmock
fi

pushd ./test

rm -rf build || true

# from https://dr-kino.github.io/2019/12/22/test-coverage-using-gtest-gcov-and-lcov/
mkdir -p build && cd build && cmake ..
make init
make gcov
make lcov

popd

find ./test/build/lcoverage